DROP DATABASE IF EXISTS feelings_DB;

CREATE DATABASE feelings_DB;

USE feelings_DB;

CREATE TABLE feelings (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) NOT NULL,
  emotion VARCHAR(45) NOT NULL,
  notes VARCHAR(500) NOT NULL,
   PRIMARY KEY (id)
);