DROP DATABASE IF EXISTS dayr8;

CREATE DATABASE dayr8;

USE dayr8;

CREATE TABLE feelings (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR (45) NOT NULL,
  emotion VARCHAR(45) NOT NULL,
  notes VARCHAR(500) NOT NULL,
   PRIMARY KEY (id)
);